from typing import TypedDict, List, Annotated
import operator
from src.tools.vault_tools import ComponentGroup

class SolutionFunction(TypedDict):
    # Identity of the persisted record. Empty string for a brand-new function;
    # set to an existing registry id when this function is a merge into it.
    solution_function_id: str
    name: str
    business_description: str
    primary_objects: List[str]
    component_groups: List[str]
    complexity_score: int

class DomainState(TypedDict):
    # Input data from the Clusterer
    candidate_domain: List[ComponentGroup]

    # Generated by the Synthesizer
    proposed_functions: List[SolutionFunction]

    # Populated by the Validator
    validation_feedback: str
    is_valid: bool

    # Structured overlap data populated by the Validator when a proposed
    # function is too similar to an existing registry function. Each entry
    # describes the existing function the Synthesizer must merge into.
    registry_matches: List[dict]

    # Gray-zone pairs deferred by the Validator to the Adjudicator node.
    # Each entry: {"proposed": <SolutionFunction dict>,
    #              "candidates": List[(<registry record>, <ScoreBreakdown>)]}.
    # No reducer (overwrite): the Validator fully replaces each pass; the
    # Adjudicator clears to [] after resolving.
    gray_zone_pairs: List[dict]

    # Adjudicator memory: (proposed_name, candidate_id) pairs the Adjudicator
    # has already ruled NO-MERGE on. The Validator consults this set so a pair
    # that was ruled distinct is never re-deferred on a later retry (which would
    # cost a repeat Adjudicator LLM call to reach the same verdict).
    # operator.add reducer accumulates entries across passes.
    resolved_no_merges: Annotated[List[dict], operator.add]

    # Loop control: count of failed validations (retries) so far.
    # operator.add reducer accumulates the +1 the validator returns on failure.
    retry_count: Annotated[int, operator.add]
