from typing import TypedDict, List, Annotated
import operator
from src.tools.vault_tools import ComponentGroup

class SolutionFunction(TypedDict):
    name: str
    business_description: str
    primary_objects: List[str]
    component_groups: List[str]
    complexity_score: int

class DomainState(TypedDict):
    # Input data from the Clusterer
    candidate_domain: List[ComponentGroup] 
    
    # Generated by the Synthesizer
    proposed_functions: List[SolutionFunction] 
    
    # Populated by the Validator
    validation_feedback: str 
    is_valid: bool 
    
    # Loop control
    retry_count: Annotated[int, operator.add] 
