from typing import TypedDict, List, Annotated
import operator

class SolutionFunction(TypedDict):
    name: str
    business_description: str
    primary_objects: List[str]
    component_groups: List[str]
    complexity_score: str

class DomainState(TypedDict):
    # Input data from the Clusterer
    candidate_domain: dict 
    
    # Generated by the Synthesizer
    proposed_functions: List[SolutionFunction] 
    
    # Populated by the Validator
    validation_feedback: str 
    is_valid: bool 
    
    # Loop control
    retry_count: Annotated[int, operator.add]